name: Deploy csr.sovisys.com to Hetzner

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: ${{ secrets.HETZNER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            set -e

            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            cd /var/www/csr.sovisys.com

            echo "➡️  Pulling latest changes from GitHub..."
            git pull

            echo "➡️  Installing dependencies..."
            pnpm install

            echo "➡️  Building the project..."
            pnpm build

            echo "✅ csr.sovisys.com deployment successful!"
